version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
        - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=CHANGEME

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=vmg@arachnion.de
      - PGADMIN_DEFAULT_PASSWORD=CHANGEME
    ports:
      - 80:80
    links:
      - postgres
